forward_model:
  _target_: diffusha.model.diffusion_model.ForwardModel
  state_dim: 44
  action_dim: 2
  next_state_dim: 44
  hidden_dim: 256
  deterministic: true


forward_trainer:
  device: "cuda:0"
  lr: 0.0001
  save_dir: data/fwd_model
  exp_name: 'Forward_sa'
  seed: 42

  track: true
  wandb_project_name: 'diffusion_test'
  wandb_entity: null 
  wandb_logdir: data/wandb_log
  save_every: 1000
