### Root Dir 
root_dir: ${hydra.runtime.cwd}

wandb_project_name: 'expert_data_collection'
wandb_log_dir: '${root_dir}/wandb_log/'
wandb_entity: null
track: true
save_video: true                  # Flag to save video during data collection
num_vis_episodes: 100
task_name: 'SimpleChargerPlug-v1'   ### <------------------ Change this # optional: SimplePegInsertion-v1

## Task Specification 
exp_name: '${task_name}'     ### <------------------ Change this
# exp_name: 'DC_ChargePlug_2_Task'    
env_id: '${task_name}' ### <------------------ Change this 
# env_id: 'SimpleChargerPlug-v1'
obs_mode: "state_dict" # there is also "state_dict", "rgbd", ...
control_mode: "pd_joint_delta_pos"  # there is also "pd_joint_delta_pos", ...
render_mode: "rgb_array"
n_env: 1


load_model: true
# Path to expert checkpoint from scripts/maniskill/train_expert_maniskill_charger.py
model_path: "${root_dir}/model_param/weight/charger_expert/<RUN_DIR>/<CHECKPOINT>.pth"

seed: 42

randp: 0.1 # <------------------ Change this
perturb_method: 'noisy' # <------------------ Change this

data_dir: "${root_dir}/dataset/Charge/${task_name}"                    # Path to store generated data <------------------ Change this  
# data_dir: "${root_dir}/data/expert_charger_2_task"                # Path to store generated data <------------------ Change this  

chunk_size: 10000                # Size of data chunks
desired_num_chunks: 15
maximum_steps: 1000000          # Number of transitions to collect

# valid_return_threshold: 250      # Threshold for valid episode returns

device: 'cuda:0'




