# Paths are relative to the repository root. Training code may override save_dir.
forward_model:
  _target_: diffusha.model.diffusion_model.ForwardModel
  state_dim: 35
  action_dim: 8
  next_state_dim: 35
  hidden_dim: 256
  deterministic: true
  action_range: [
    [-2.5,-2.5, -10.,-10. , -6.2831855,-10., -0.,-0.],
    [2.5,2.5, 10.,10. , 6.2831855,10., 1.,1.]
    ]

forward_trainer:
  device: "cuda:1"
  lr: 0.0001
  save_dir: data/fwd_model
  exp_name: 'Forward_peg_v1'
  seed: 42

  track: true
  wandb_project_name: 'diffusion_test'
  wandb_entity: null 
  wandb_logdir: model_param/log/fwd_model
  save_every: 1000
